CREATE TABLE IF NOT EXISTS product (
id UUID DEFAULT UUID(),
name CHARACTER VARYING(10) NOT NULL,
description CHARACTER VARYING(30) NOT NULL,
price NUMERIC(11, 2) NOT NULL,
created TIMESTAMP WITH TIME ZONE NOT NULL,

PRIMARY KEY(id)
);
